String name = "hello-world"
String tag = "1.0"
node {
    stage ('Build Dockerfile'){
        sh """
        cd /var/lib/jenkins/spring-boot-hello-world
        docker build --tag ${name}:${tag} .
        """
    }
}
